name: Anypoint CLI API Governance

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cli:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Anypoint CLI
        run: npm install -g anypoint-cli-v4

      - name: Scan API Spec with API Governance
        run: >
          anypoint-cli-v4 governance:api:validate
          c8816973-0064-4b8a-80cb-480706d35c4a/quotes-api/1.0.1
          --remote-rulesets c8816973-0064-4b8a-80cb-480706d35c4a/custom-best-practices/1.0.0
          --remote --client_id deda28841acc4c77bf753103e5053712 
          --client_secret 3de524d2DDD24e73b51768cfB2029446 --environment Sandbox
